language: node_js
node_js:
- 0.11
before_script:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
- sudo apt-get update;
- sudo apt-get install gcc-4.8 g++-4.8;
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20;
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20;
- sudo g++ --version;
- sudo apt-get update -qq;
- npm install -g grunt-cli
script:
- grunt build
after_success:
- chmod -R 777 .travis-build.sh
- ./.travis-build.sh
env:
  global:
    secure: OJbAIG1yFzfU7JTNDzCVxU9+33MjduhvWFkEsIPoUmLe/reKPug11OIFBAnriX7KVnlGBQ8oNIeN5n0o0rZN9FLLSEVGXAviT0BMCnEzJraCFOjrYW6Hf2dPIyuEIzopIVfY9hTXmOJcUstyx3//Iu0pWG/5+StyvK4dK7nR3Kk=
